openapi: 3.0.0
info:
  title: IRS Domain Data - Business Taxpayer Account - Business Account Role
  description: >-
    Business Account Role mictoservice for IRS Business Taxpayer Account REST
    APIs
  version: '1.06.03'
servers:
  - url: /bus-acct-svcs-role/api/v1/
paths:
  /business-account-role:
    post:
      summary: Adds a new Authorized User to a Business Account
      description: >-
        Add a new Business Account Role entry associating a Person with a
        BusinessEntity with a specific role, and a date by when the "nomination"
        is to be accepted. The Role Status will typically be "Pending".
      operationId: addBusinessAccountRole
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
      requestBody:
        description: >-
          Add a new Business Account Role entry associating a Person with an
          existing Organization
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessAccountRole'
            examples:
              businessAccountRoleExample:
                $ref: '#/components/examples/BusinessAccountRoleExample'
        required: true
      responses:
        '201':
          description: The User was added successfully to the Business Account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAccountRole'
              examples:
                businessAccountRoleExample:
                  $ref: '#/components/examples/BusinessAccountRoleExample'
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - business account role
    put:
      summary: Updates an authorized user associated with the business taxpayer account
      description: >-
        - Update: Update the Business Account Role with a  Role Start Date,
        update the status to "Active" OR if the Acceptance Expiration Date is
        past, and the "nomination" is expired, set the status to "Expired" OR
        change the Acceptance Expiration Date  - Delete:  Remove an existing
        Business Account Role instance by setting the status to "Inactive"  In
        all cases, there will be an Update Date when the transaction happened,
        set to the current system date, and the Source of the update will be set
        to the application calling the API - e.g. "BOLA"; The Authorization
        Start and End dates limit the Tax dates to which the role has access
      operationId: updateBusinessAccountRole
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
      requestBody:
        description: Update a Business Account Role entry
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessAccountRole'
        required: true
      responses:
        '200':
          description: The User was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAccountRole'
              examples:
                businessAccountRoleExample:
                  $ref: '#/components/examples/BusinessAccountRoleExample'
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - business account role
  /business-account-role/{guid}:
    summary: Business Account Roles assigned to Users by GUID
    description: Used to retrieve or update Business Account Roles when the GUID is known
    parameters:
      - $ref: '#/components/parameters/enterpriseBusCorrelationId'
      - $ref: '#/components/parameters/guid'
      - $ref: '#/components/parameters/apiCaller'
    get:
      summary: Retrieves a Business Account Role by GUID
      description: When a business account role is known, retrieve it
      operationId: getBusinessAccountRoleByGUID
      responses:
        '200':
          description: The Business Account Role was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAccountRole'
              examples:
                businessAccountRoleExample:
                  $ref: '#/components/examples/BusinessAccountRoleExample'
        '204':
          description: User Role not found
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - business account role
  /business-account-role/representatives:
    summary: get Authorized Representatives for a given Organization
    get:
      summary: Returns a list of Persons associated with an Organization
      description: >-
        Returns a list of of one or more individuals who are authorized to
        represent the business to IRS, including their role, effective dates and
        dates where they have access to the account, and who meet the filter
        conditions requested
      operationId: getAuthorizedRepresentative
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/ein'
        - $ref: '#/components/parameters/optionalSSN'
        - $ref: '#/components/parameters/businessAccountRoles'
        - $ref: '#/components/parameters/apiCaller'
      responses:
        '200':
          description: A list of representatitives for the account.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusinessAccountRole'
              examples:
                businessAccountRepresentativesExample:
                  $ref: '#/components/examples/BusinessAccountRepresentativesExample'
        '204':
          description: No represenatives found for this organization and roles
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - business account role
  /business-account-role/organizations:
    summary: Returns a list of Organizations associated with a User
    description: >-
      Returns a list of Businesses who the specified person (SSN) is authorized
      to represent, including their roles, effective dates and tax years
    get:
      summary: Returns Organizations associated with a user
      description: >-
        Returns a list of Organizations who the specified person (SSN) is
        authorized to represent, including their roles, effective dates and tax
        years
      operationId: getAuthorizedOrganization
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/SSN'
        - $ref: '#/components/parameters/businessAccountRoleStatuses'
        - $ref: '#/components/parameters/apiCaller'
      responses:
        '200':
          description: A list of accounts for the representative
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusinessAccountRole'
              examples:
                businessAccountOrganizationsExample:
                  $ref: '#/components/examples/BusinessAccountOrganizationsExample'
        '204':
          description: No accounts found for this representative and status
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - business account role
  /business-account-role/authorizations:
    summary: Provides list of authorizations for roles and entity types
    description: Provides list of authorizations for roles and entity types
    get:
      summary: return a list of authorizations for the role and entity type
      operationId: getAuthorizations
      parameters:
        - $ref: '#/components/parameters/businessAccountRoleName'
        - $ref: '#/components/parameters/entityType'        
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
      responses:
        '200':
          description: A list of authorizations for the Business Account Role
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleAuthorization'
              examples:
                authorizationsExample:
                  $ref: '#/components/examples/AuthorizationsExample'
        '204':
          description: No authorizations found for this role, entity type and status
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - business account role, authorization
  /business-account-role/version:
    get:
      summary: Returns a version number for the API
      description: Returns a version number of the API and the database
      operationId: BARVersion
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
      responses:
        '200':
          description: Here is the version information for this API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiVersion'
      tags:
        - business account role
components:
  schemas:
    enterpriseBusCorrelationId:
      type: string
      pattern: >-
        [0-9a-zA-Z]{8}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{12}:[a-zA-Z0]{0,5}:[a-zA-Z0-9.*:]{0,19}:(T|B|O)
      example: 550e8400-e29b-41d4-a716-446655440000:AMS00:System1:T
    apiVersion:
      type: object
      properties:
        buildVersion:
          type: string
          example: v1.04.01
        debugLevel:
          type: integer
        environment:
          type: string
          enum:
            - Development
            - Test
            - Pre-Production
            - Production
        controller:
          type: string
          example: BusinessAccountRole
        buildDateTime:
          type: string
          format: date-time
        specificationVersion:
          type: string
          example: v1.04
        entityCount:
          type: integer
          example: 152726
        requestHost:
          type: string
          example: irs-edp-dev-api.a.cc.irs.gov
        requestUri:
          type: string
          example: /api/v1/tax-modules/version
        httpVerb:
          type: string
          example: GET
        serviceStart:
          type: string
          format: date-time
          example: '2024-01-15T18:29:31.820+00:00'
        serviceEnd:
          type: string
          format: date-time
          example: '2024-01-15T18:29:33.314+00:00'
        serviceElapsedTimeSec:
          type: number
          example: 1.49
    Organization:
      type: object
      properties:
        guid:
          $ref: '#/components/schemas/GUID'
        ein:
          $ref: '#/components/schemas/EmployerIdentificationNumber'
        organizationName:
          type: string
          example: ABCD Corporation
        organizationNameControl:
          type: string
          example: ABCD
        TINType:
          $ref: '#/components/schemas/TINType'
        parentEIN:
          $ref: '#/components/schemas/EmployerIdentificationNumber'
        entityType:
          $ref: '#/components/schemas/EntityType'
        LLCIndicator:
          type: string
          enum:
            - Single Member
            - Multiple Member
            - 'False'
        soleProprietorTIN:
          $ref: '#/components/schemas/SocialSecurityNumber'
        fiscalYear:
          type: integer
          format: year
        fiscalMonth:
          type: integer
        NAICSCodes:
          type: array
          items:
            $ref: '#/components/schemas/NAICSCode'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        telephoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/TelephoneNumber'
        complianceStatus:
          $ref: '#/components/schemas/ComplianceStatus'
    ComplianceStatus:
      type: integer
      description: Compliance status of a record taking integer values
    TINType:
      type: string
      enum:
        - '0'
        - '1'
        - '2'
    NAICSCode:
      type: object
      properties:
        NAICSCode:
          type: string
          example: '54124'
        NAICSValidityIndicator:
          type: string
          example: '01'
        taxReturnYear:
          $ref: '#/components/schemas/TaxYear'
    BusinessAccountRoleName:
      type: string
      description: The role a user plays in association with an organization
      enum:
        - Designated Officer
        - Designated Employee
        - Sole Proprietor
        - Partner
        - Shareholder
        - Clean Energy Officer
        - Clean Energy Delegate
        - Clean Energy Third Party User
        - Clean Energy-Manufacturer Employee
        - Clean Energy-Dealer Employee
        - Clean Energy-Elective Payments Employee
        - Clean Energy Unassigned
    Address:
      type: object
      properties:
        addressType:
          type: string
          enum:
            - Mailing
            - Physical
        careOfName:
          type: string
          example: Jonathan Dean
        streetAddress:
          type: string
          example: 2034 Main St
        city:
          type: string
          example: Brownsville
        state:
          type: string
          example: Alabama
        postalCode:
          type: string
          example: '3045600000000'
        foreignAddress:
          type: string
          example: 23 Rue Martinique
        country:
          $ref: '#/components/schemas/CountryCode'
    BusinessTitle:
      type: string
      enum:
        - President
        - Director
        - Vice President
        - Chief Financial Officer
        - Chief Operating Officer
        - Chief Officer
        - Secretary
        - Treasurer
        - Partner
        - Limited Partner
        - General Partner
        - Member
        - Managing Member
        - Sole Member
        - Beneficiary
        - Board Member
        - Trustee
        - LLC Managing Member
        - Other
    Person:
      type: object
      required:
        - lastName
        - firstName
        - ssn
      properties:
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        ssn:
          $ref: '#/components/schemas/SocialSecurityNumber'
      example:
        firstName: Joan
        middleName: Mary
        lastName: Richards
        ssn: '135792468'
    SocialSecurityNumber:
      type: string
      format: password
      pattern: ^[0-9]{9}$
    BusinessAccountRole:
      type: object
      description: >-
        The association between a business and a person playing a role with
        privileges on that business taxpayer account. The EIN+SSN+Role uniquely
        identify a Business Account Role.
      required:
        - person
        - ein
        - role
        - roleStatus
      properties:
        guid:
          $ref: '#/components/schemas/GUID'
        ein:
          $ref: '#/components/schemas/EmployerIdentificationNumber'
        person:
          $ref: '#/components/schemas/Person'
        businessTitle:
          $ref: '#/components/schemas/BusinessTitle'
        role:
          $ref: '#/components/schemas/BusinessAccountRoleName'
        roleStatus:
          $ref: '#/components/schemas/RoleStatus'
        removalReason:
          type: string
          enum:
            - 'User is no longer employed by the entity'
            - 'User is inactive'
            - 'User can no longer legally bind the entity'
        emailAddresses:
          type: array
          uniqueItems: true
          minItems: 0
          maxItems: 32
          items:
            $ref: '#/components/schemas/EMailAddress'
        accessPeriods:
          type: array
          items:
            $ref: '#/components/schemas/taxAccountAccessPeriod'
        nominationDate:
          type: string
          format: date-time
        nominationExpirationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
        lastValidationDate:
          type: string
          format: date-time
        validationEndDate:
          type: string
          format: date-time
        complianceStatus:
          $ref: '#/components/schemas/ComplianceStatus'
      example:
        guid: a81bc81b-dead-4e5d-abff-90865d1e13b1
        ein: '987654321'
        person:
          firstName: Jennifer
          middleName: C
          lastName: Davids
          ssn: '246813579'
        businessTitle: Director
        role: Sole Proprietor
        roleStatus: Active
        emailAddresses:
          - emailAddressPurpose: EPE
            emailPreference: true
            emailAddress: jennifer.c.davids@abcd.com
        accessPeriods:
          - accessPeriodStartDate: 01/01/2020
            accessPeriodEndDate: 12/31/2020
          - accessPeriodStartDate: 01/01/2022
            accessPeriodEndDate: 12/31/2022
        nominationDate: 07/01/2022
        nominationExpirationDate: 07/31/2022
        updateDate: 12/31/2022
        lastValidationDate: 01/01/2023
        validationEndDate: 12/31/2023
    RoleStatus:
      type: string
      enum:
        - Active
        - Pending
        - Expired
        - Declined
        - Removed
        - Pending Reviewer Approval
        - Pending PIN Validation 
        - Failed PIN Validation
    taxAccountAccessPeriod:
      type: object
      properties:
        accessPeriodStartDate:
          type: string
          format: date-time
        accessPeriodEndDate:
          type: string
          format: date-time
    RoleAuthorization:
      type: string
      example: 'txp.bta.api.accountBalance'
    
    EmployerIdentificationNumber:
      type: string
      format: password
      pattern: ^[0-9]{9}$
      example: '123456789'
    EntityType:
      type: string
      enum:
        - C Corporation
        - S Corporation
        - Partnership
        - Sole Proprietorship
        - Trust
        - Tax Exempt Organization
        - Estate
        - Government Entity

    TaxYear:
      type: integer
      format: int32
      minimum: 1970
      description: The Tax Year for which the query is run
    TaxMonth:
      type: integer
      format: int32
    TaxPeriod:
      type: string
      format: ^(19|20)\d{2}(d{2})$
      description: >-
        Date representing the last day of the month for which the tax was
        assessed
    CountryCode:
      type: string
      example: US
    TelephoneNumber:
      type: object
      properties:
        telephoneNumberType:
          type: string
          enum:
            - Headquarters
            - Mobile
            - Sales
        telephoneCountryCode:
          type: string
          format: ^\+'[0-9]{1,3}$
          example: '+1'
        areaCode:
          type: string
          format: ^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$
          example: '202'
        phoneNumber:
          type: string
          format: ^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$
          example: '123456'
    EMailAddress:
      type: object
      required:
        - emailAddressPurpose
        - emailPreference
        - emailAddress
      properties:
        emailAddressPurpose:
          type: string
          enum:
            - EPE
            - Accounting
            - Tax
        emailPreference:
          type: boolean
        emailAddress:
          type: string
          format: email
          example: john.doe@abc.com
    GUID:
      type: string
      format: uuid
      description: >-
        The GUID of the Business Account Role, representing an association of a
        person to an organization with a specific role
  examples:
    AuthorizationsExample:
      value:
        roleAuthorizations:
          - roleAuthorization: 'txp.bta.api.accountBalance'
          - roleAuthorization: 'txp.bta.api.getTranscript'
    BusinessAccountRoleExample:
      value:
        guid: 42a16229-7855-4603-a28b-721e4b5f6c8c
        ein: '958473621'
        person:
          firstName: Jorge
          middleName: Santiago
          lastName: Valera
          ssn: '135782468'
        businessTitle: Vice President
        role: Designated Officer
        roleStatus: Active
        emailAddresses:
          - emailAddressPurpose: EPE
            emailPreference: true
            emailAddress: jorge.s.valera@apex.com
        accessPeriods:
          - accessPeriodStartDate: 01/01/2020T00:00:00.004Z
            accessPeriodEndDate: 12/31/2020T00:00:00.004Z
          - accessPeriodStartDate: 01/01/2022T00:00:00.004Z
            accessPeriodEndDate: 12/31/2022T00:00:00.004Z
        nominationDate: 07/01/2022T00:00:00.004Z
        nominationExpirationDate: 07/31/2022T00:00:00.004Z
        updateDate: 12/31/2022T00:00:00.004Z
        lastValidationDate: 01/01/2023T00:00:00.004Z
        validationEndDate: 12/31/2023T00:00:00.004Z
    BusinessAccountRepresentativesExample:
      value:
        - guid: 42a16229-7855-4603-a28b-721e4b5f6c8c
          ein: '958473621'
          person:
            firstName: Jorge
            middleName: Santiago
            lastName: Valera
            ssn: '135782468'
          businessTitle: Vice President
          role: Designated Officer
          roleStatus: Active
          emailAddresses:
            - emailAddressPurpose: EPE
              emailPreference: true
              emailAddress: jorge.s.valera@apex.com
          accessPeriods:
            - accessPeriodStartDate: 01/01/2020T00:00:00.004Z
              accessPeriodEndDate: 12/31/2020T00:00:00.004Z
            - accessPeriodStartDate: 01/01/2022T00:00:00.004Z
              accessPeriodEndDate: 12/31/2022T00:00:00.004Z
          nominationDate: 07/01/2022T00:00:00.004Z
          nominationExpirationDate: 07/31/2022T00:00:00.004Z
          updateDate: 12/31/2022T00:00:00.004Z
          lastValidationDate: 01/01/2023T00:00:00.004Z
          validationEndDate: 12/31/2023T00:00:00.004Z
        - guid: 84a16232-7840-4612-x28c-721e4b5f7d9d
          ein: '958473621'
          person:
            firstName: Barbara
            middleName: Smith
            lastName: Taylor
            ssn: '246813579'
          businessTitle: Director
          role: Designated Employee
          roleStatus: Active
          emailAddresses:
            - emailAddressPurpose: Accounting
              emailPreference: false
              emailAddress: barbara.s.taylor@apex.com
          accessPeriods:
            - accessPeriodStartDate: 01/01/2021T00:00:00.004Z
              accessPeriodEndDate: 12/31/2021T00:00:00.004Z
            - accessPeriodStartDate: 01/01/2022T00:00:00.004Z
              accessPeriodEndDate: 12/31/2022T00:00:00.004Z
          nominationDate: 07/01/2022T00:00:00.004Z
          nominationExpirationDate: 07/31/2022T00:00:00.004Z
          updateDate: 12/31/2022T00:00:00.004Z
          lastValidationDate: 01/01/2023T00:00:00.004Z
          validationEndDate: 12/31/2023T00:00:00.004Z
    BusinessAccountOrganizationsExample:
      value:
        - guid: 42a16229-7855-4603-a28b-721e4b5f6c8c
          ein: '958473621'
          person:
            firstName: Jorge
            middleName: Santiago
            lastName: Valera
            ssn: '135782468'
          businessTitle: Vice President
          role: Designated Officer
          roleStatus: Active
          emailAddresses:
            - emailAddressPurpose: EPE
              emailPreference: true
              emailAddress: jorge.s.valera@apex.com
          accessPeriods:
            - accessPeriodStartDate: 01/01/2020T00:00:00.004Z
              accessPeriodEndDate: 12/31/2020T00:00:00.004Z
            - accessPeriodStartDate: 01/01/2022T00:00:00.004Z
              accessPeriodEndDate: 12/31/2022T00:00:00.004Z
          nominationDate: 07/01/2022T00:00:00.004Z
          nominationExpirationDate: 07/31/2022T00:00:00.004Z
          updateDate: 12/31/2022T00:00:00.004Z
          lastValidationDate: 01/01/2023T00:00:00.004Z
          validationEndDate: 12/31/2023T00:00:00.004Z
        - guid: f47ac10b-2ce3-4242-a842-01002764c093
          ein: '4202003415'
          person:
            firstName: Jorge
            middleName: Santiago
            lastName: Valera
            ssn: '135782468'
          businessTitle: Director
          role: Designated Employee
          roleStatus: Active
          emailAddresses:
            - emailAddressPurpose: Tax
              emailPreference: false
              emailAddress: jvalera@nadir.com
          accessPeriods:
            - accessPeriodStartDate: 01/01/2019T00:00:00.004Z
              accessPeriodEndDate: 12/31/2022T00:00:00.004Z
          nominationDate: 01/01/2019T00:00:00.004Z
          nominationExpirationDate: 03/01/2019T00:00:00.004Z
          updateDate: 12/31/2022T00:00:00.004Z
          lastValidationDate: 01/01/2023T00:00:00.004Z
          validationEndDate: 12/31/2023T00:00:00.004Z
    OrganizationExample:
      value:
        guid: 21b13119-7855-4603-a28b-721e4b5f8d9d
        ein: '958473621'
        organizationName: ABCD Corporation
        organizationNameControl: ABCD
        TINType: '2'
        parentEIN: '202543210'
        entityType: C Corporation
        LLCIndicator: 'False'
        soleProprietorTIN: null
        fiscalYear: 2022
        fiscalMonth: 12
        NAICSCodes:
          - NAICSCode: '541512'
            NAICSValidityIndicator: '03'
            taxReturnYear: 2022
          - NAICSCode: '541511'
            NAICSValidityIndicator: '04'
            taxReturnYear: 2022
        addresses:
          - addressType: Mailing
            careOfName: John Smith
            streetAddress: 2003 Pine St
            city: Smalltown
            state: Georgia
            postalCode: '30456'
            foreignAddress: null
            country: US
          - addressType: Headquarters
            careOfName: Jean Dewberry
            streetAddress: 100 Willow Ln
            city: Smalltown
            state: Georgia
            postalCode: '304550000000'
            foreignAddress: null
            country: US
        telephoneNumbers:
          - telephoneNumberType: Headquarters
            telephoneCountryCode: '1'
            areaCode: '404'
            phoneNumber: '123456'
    SubsidiariesExample:
      value:
        - guid: 21b13119-7855-4603-a28b-721e4b5f8d9d
          ein: '958473621'
          organizationName: ABCD Corporation
          organizationNameControl: ABCD
          TINType: '2'
          parentEIN: '202543210'
          entityType: C Corporation
          LLCIndicator: 'False'
          soleProprietorTIN: null
          fiscalYear: 2022
          fiscalMonth: 12
          NAICSCodes:
            - NAICSCode: '541512'
              NAICSValidityIndicator: '06'
              taxReturnYear: '2022'
            - NAICSCode: '541511'
              NAICSValidityIndicator: '02'
              taxReturnYear: '2022'
          addresses:
            - addressType: Mailing
              careOfName: John Smith
              streetAddress: 2003 Pine St
              city: Smalltown
              state: Georgia
              postalCode: '304561234000'
              foreignAddress: null
              country: US
            - addressType: Physical
              careOfName: Jean Dewberry
              streetAddress: 100 Willow Ln
              city: Smalltown
              state: Georgia
              postalCode: '304551234001'
              foreignAddress: null
              country: US
          telephoneNumbers:
            - telephoneNumberType: Headquarters
              telephoneCountryCode: '1'
              areaCode: '404'
              phoneNumber: '123456'
        - guid: 21b13119-8944-4603-a28b-832e5b5f8d9d
          ein: '123456789'
          organizationName: Zenith Corporation
          organizationNameControl: ZENI
          TINType: '2'
          parentEIN: '202543210'
          entityType: C Corporation
          LLCIndicator: 'False'
          soleProprietorTIN: null
          fiscalYear: 2022
          fiscalMonth: 12
          NAICSCodes:
            - NAICSCode: '541519'
              NAICSValidityIndicator: '01'
              taxReturnYear: '2022'
            - NAICSCode: '541618'
              NAICSValidityIndicator: '05'
              taxReturnYear: '2022'
          addresses:
            - addressType: Mailing
              careOfName: null
              streetAddress: 2003 Niblick Dr
              city: Manassas
              state: Virginia
              postalCode: '20136'
              foreignAddress: null
              country: US
            - addressType: Mailing
              careOfName: Charles Bristow
              streetAddress: 506 Oakwood Rd
              city: Columbia
              state: Maryland
              postalCode: '210441234001'
              foreignAddress: null
              country: US
          telephoneNumbers:
            - telephoneNumberType: Headquarters
              telephoneCountryCode: '+1'
              areaCode: '443'
              phoneNumber: '123456'
    OrganizationsExample:
      value:
        - guid: 21b13119-7855-4603-a28b-721e4b5f8d9d
          ein: '958473621'
          organizationName: ABCD Corporation
          organizationNameControl: ABCD
          TINType: '2'
          parentEIN: '202543210'
          entityType: C Corporation
          LLCIndicator: 'False'
          soleProprietorTIN: null
          fiscalYear: 2022
          fiscalMonth: 12
          NAICSCodes:
            - NAICSCode: '541512'
              NAICSValidityIndicator: '06'
              taxReturnYear: '2022'
            - NAICSCode: '541511'
              NAICSValidityIndicator: '02'
              taxReturnYear: '2022'
          addresses:
            - addressType: Mailing
              careOfName: John Smith
              streetAddress: 2003 Pine St
              city: Smalltown
              state: Georgia
              postalCode: '304561234000'
              foreignAddress: null
              country: US
            - addressType: Physical
              careOfName: Jean Dewberry
              streetAddress: 100 Willow Ln
              city: Smalltown
              state: Georgia
              postalCode: '304551234001'
              foreignAddress: null
              country: US
          telephoneNumbers:
            - telephoneNumberType: Headquarters
              telephoneCountryCode: '1'
              areaCode: '404'
              phoneNumber: '123456'
        - guid: 21b13119-8944-4603-a28b-832e5b5f8d9d
          ein: '123456789'
          organizationName: Zenith Corporation
          organizationNameControl: ZENI
          TINType: '2'
          parentEIN: '202543210'
          entityType: C Corporation
          LLCIndicator: 'False'
          soleProprietorTIN: null
          fiscalYear: 2022
          fiscalMonth: 12
          NAICSCodes:
            - NAICSCode: '541519'
              NAICSValidityIndicator: '01'
              taxReturnYear: '2022'
            - NAICSCode: '541618'
              NAICSValidityIndicator: '05'
              taxReturnYear: '2022'
          addresses:
            - addressType: Mailing
              careOfName: null
              streetAddress: 2003 Niblick Dr
              city: Manassas
              state: Virginia
              postalCode: '20136'
              foreignAddress: null
              country: US
            - addressType: Mailing
              careOfName: Charles Bristow
              streetAddress: 506 Oakwood Rd
              city: Columbia
              state: Maryland
              postalCode: '210441234001'
              foreignAddress: null
              country: US
          telephoneNumbers:
            - telephoneNumberType: Headquarters
              telephoneCountryCode: '+1'
              areaCode: '443'
              phoneNumber: '123456'
  parameters:
    enterpriseBusCorrelationId:
      name: enterpriseBusCorrelationId
      description: Enterprise Business Correlation ID
      in: header
      required: false
      schema:
        $ref: '#/components/schemas/enterpriseBusCorrelationId'
    apiCaller:
      name: callingApplication
      description: >-
        the application that orginally calls the API in a consistent, agreed
        upon naming convention
      in: header
      required: false
      schema:
        type: string
      example: Business-Online-Account
    ein:
      name: ein
      description: The Employer Identification Number of the Organization
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/EmployerIdentificationNumber'
    parentEIN:
      name: parentEIN
      description: The EIN of the organization whose subsidiaries are being queried for
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/EmployerIdentificationNumber'
    SSN:
      in: header
      description: >-
        The Social Security Number of the person with an authorized role
        associated with the Organization.
      name: ssn
      required: true
      schema:
        $ref: '#/components/schemas/SocialSecurityNumber'
    tin:
      in: header
      description: >-
        The TIN of the person/organization with an authorized role associated
        with the Organization.
      name: tin
      required: true
      schema:
        $ref: '#/components/schemas/SocialSecurityNumber'
    optionalSSN:
      in: header
      description: >-
        The Social Security Number of the person with an authorized role
        associated with the Organization.
      name: ssn
      required: false
      schema:
        $ref: '#/components/schemas/SocialSecurityNumber'
    taxYears:
      in: header
      description: >-
        The Tax Years for which Tax Modules or Tax Transactions are being
        requested.
      name: taxYear
      schema:
        type: array
        items:
          type: string
    businessAccountRoles:
      name: businessAccountRoles
      description: 'List of possible Roles for the user.'
      in: header
      required: false
      schema:
        type: array
        items:
          type: string
    businessAccountRoleStatuses:
      name: businessAccountRoleStatuses
      description: List of possible Role Statuses
      in: header
      required: false
      schema:
        type: array
        items:
          type: string
    eins:
      name: eins
      description: List of eins
      in: header
      required: true
      schema:
        type: array
        items:
          type: string
    guid:
      name: guid
      description: >-
        The GUID of the Business Account Role, representing an association of a
        person to an organization with a specific role
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/GUID'
    createDate:
      name: createDate
      in: header
      description: the e-signature creation date requested for
      required: false
      schema:
        type: string
        format: date
    businessAccountRoleName:
      name: businessAccountRoleName
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/BusinessAccountRoleName'
    entityType:
      name: entityType
      in: header
      required: false
      schema:
        $ref: '#/components/schemas/EntityType'
  responses:
    BadRequest:
      description: This request was not formed correctly.
    PreconditionFailed:
      description: One of the required parameters is not correct.
    GeneralError:
      description: An error occurred
    VolumeExceeds:
      description: >-
        String.format("Too many records returned (%d) for the ein, max size:
        %d", recordsdatasetSize, API_MAX_DATASET_RETURN_LIMIT)
  headers:
    X-RateLimit-Limit:
      description: Request limit per hour
      schema:
        type: integer
      example: 100
    X-RateLimit-Remaining:
      description: Remaining requests for the hour
      schema:
        type: integer
      example: 94
  links: {}
  callbacks: {}
